---
- name: Install nginx and php
  hosts: type_web:type_php
  gather_facts: true
  become: yes
  tasks:
    - name: Including roles
       roles:
        - awslogs
        - php-fpm
        - phpmyadmin
        - nginx
- name: Intall DB
  hosts: type_db
  gather_facts: true
  become: yes
  tasks:
    - name: Including roles
      include_role:
        name: mariadb
